/** @typedef Transaction
 * @property {string} [date]
 * @property {string} [time]
 * @property {string} [timeZone]
 * @property {string} [description]
 * @property {string} [currency]
 * @property {number} [gross]
 * @property {number} [fee]
 * @property {number} [net]
 * @property {number} [balance]
 * @property {string} transactionId
 * @property {string} [fromEmail]
 * @property {string} [name]
 * @property {string} [bankName]
 * @property {string} [bankAccount]
 * @property {string} [shippingAndHandlingAmount]
 * @property {number} [salesTax]
 * @property {string} [invoiceId]
 * @property {string} [referenceId]
 */
